<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOeCTTRc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOeCTTRc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOeCTTRc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOeCTTRc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOeCTTRc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OeCTTRc',
    'container.build_id' => '55b3628c',
    'container.build_time' => 1583431768,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOeCTTRc');
