<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUD3HJ2A\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUD3HJ2A/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUD3HJ2A.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUD3HJ2A\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUD3HJ2A\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UD3HJ2A',
    'container.build_id' => '107f1f6e',
    'container.build_time' => 1583352844,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUD3HJ2A');
